<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title }}</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h2 { margin: 0; text-transform: uppercase; color: #2f3e2f; }
        .meta { margin-bottom: 20px; border-bottom: 1px solid #ddd; padding-bottom: 10px; }
        .meta p { margin: 4px 0; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; color: #333; }
        .footer { position: fixed; bottom: 0; left: 0; right: 0; font-size: 10px; text-align: center; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <h2>{{ $title }}</h2>
    </div>

    <div class="meta">
        @foreach($filters as $label => $val)
            <p><strong>{{ $label }}:</strong> {{ $val }}</p>
        @endforeach
    </div>

    @if(isset($summary) && $type == 'attendance')
        <h3>Guard Performance Summary</h3>
        <table class="summary-table" style="margin-bottom: 30px;">
            <thead>
                <tr>
                    <th>Guard Name</th>
                    <th>Total Days</th>
                    <th>Present</th>
                    <th>Absent</th>
                    <th>Rate</th>
                </tr>
            </thead>
            <tbody>
                @foreach($summary as $s)
                    @php
                        $rate = $s->total_logs > 0 ? round(($s->present_days / $s->total_logs) * 100) . '%' : '0%';
                    @endphp
                    <tr>
                        <td>{{ $s->guard_name }}</td>
                        <td>{{ $s->total_logs }}</td>
                        <td>{{ $s->present_days }}</td>
                        <td>{{ $s->absent_days }}</td>
                        <td>{{ $rate }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
        
        <h3>Detailed Logs</h3>
    @endif

    <table>
        <thead>
            <tr>
                @if($type === 'attendance')
                    <th>Date</th>
                    <th>Guard</th>
                    <th>Site</th>
                    <th>Entry</th>
                    <th>Exit</th>
                    <th>Status</th>
                @else
                    <th>Date</th>
                    <th>Session Type</th>
                    <th>Guard</th>
                    <th>Site</th>
                    <th>Distance</th>
                    <th>Duration</th>
                @endif
            </tr>
        </thead>
        <tbody>
            @foreach($data as $row)
            <tr>
                @if($type === 'attendance')
                    <td>{{ $row->date }}</td>
                    <td>{{ $row->guard_name }}</td>
                    <td>{{ $row->site_name }}</td>
                    <td>{{ $row->entry_time }}</td>
                    <td>{{ $row->exit_time ?? '-' }}</td>
                    <td>{{ $row->status == 1 ? 'Present' : 'Absent' }}</td>
                @else
                    <td>{{ \Carbon\Carbon::parse($row->started_at)->format('d M Y H:i') }}</td>
                    <td>{{ $row->session }}</td>
                    <td>{{ $row->guard_name }}</td>
                    <td>{{ $row->site_name ?? 'N/A' }}</td>
                    <td>{{ $row->distance }} m</td>
                    <td>
                        @if($row->ended_at)
                            {{ \Carbon\Carbon::parse($row->started_at)->diffInMinutes($row->ended_at) }} min
                        @else
                            Ongoing
                        @endif
                    </td>
                @endif
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by AI Patrolling System
    </div>
</body>
</html>
